name: curl
version: 0.1.1
# The vendor for the snap (replace 'Vendor <email@example.com>')
vendor: tetor <tetor.takashi.etou@gmail.com>
summary: cURL snappy framework
description: cURL for Snappy Ubuntu Core
icon: icon.png # A path to an icon for the package
type: framework
binaries:
  - name: curl
    exec: bin/curl
