name: curl
version: 0.1.0
# The vendor for the snap (replace 'Vendor <email@example.com>')
vendor: tetor <tetor.takashi.etou@gmail.com>
summary: cURL snappy framework
description: This is wip. Do not use plz
icon: icon.png # A path to an icon for the package
type: framework
binaries:
  - name: curl
    exec: bin/curl
